# Generated by Django 5.0.6 on 2024-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('info', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usrData',
            fields=[
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('edu', models.CharField(max_length=40)),
                ('cors', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('pswd', models.CharField(max_length=30)),
                ('usr', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
