# Generated by Django 5.0.6 on 2024-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrdata',
            name='usrid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
