# Generated by Django 5.2.7 on 2025-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0002_alter_course_category_discussion_discussionreply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=200, verbose_name='College of Graduation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('tamil_nadu', 'Tamil Nadu'), ('karnataka', 'Karnataka'), ('maharashtra', 'Maharashtra'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('others', 'Others')], max_length=20),
        ),
    ]
