# Generated by Django 5.0.6 on 2024-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0002_usrdata_usrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrid', models.IntegerField()),
                ('course', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usrdata',
            name='usrid',
        ),
        migrations.AddField(
            model_name='usrdata',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usrdata',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
