# Generated by Django 5.0.6 on 2024-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0003_cart_remove_usrdata_usrid_usrdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
