# Generated by Django 5.0.6 on 2024-08-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0004_admindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='usr',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
