# Generated by Django 5.0.6 on 2024-09-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0007_remove_usrdata_id_alter_usrdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='d_img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
