# Generated by Django 5.0.6 on 2024-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0008_course_d_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('fullname', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
    ]
