# Generated by Django 5.0.6 on 2024-09-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0009_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='msg',
            new_name='Contact_data',
        ),
    ]
