# Generated by Django 5.0.6 on 2024-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0010_rename_msg_contact_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_data',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
